# some standard testing patterns

Patterns = {
  superflip: %w(OYOGOBOWO BYBOBRBWB RYRBRGRWR GYGRGOGWG YRYGYBYOY WOWGWBWRW),
  checkerboard: %w(ORORORORO BGBGBGBGB ROROROROR GBGBGBGBG YWYWYWYWY WYWYWYWYW),
  cube_in_a_cube: %w(WWWOOWOOW RBBRBBRRR RRYRRYYYY OOOOGGOGG BYYBYYBBB WWGWWGGGG),
  cube_in_a_cube_in_a_cube: %w(WWWOOWGOW RBYRBBRRR BRYRRYYYY OOOOGGOGW BYRBYYBBB OWGWWGGGG)
}